import Head from 'next/head';
import Header from '../components/Header/Header';
import CardContainer from '../components/CardContainer/CardContainer';

import { getVideos } from '../youtube/youtube';
import style from '../styles/Home.module.css';

import { fetchWatchAgain } from '../Hasura/hasura';
import { verifyToken } from '../cookie/verifyToken';
export async function getServerSideProps(context) {
	const token = context.req.cookies.jwtToken;
	const disneyVideos = await getVideos('action movies');
	const travelVideos = await getVideos('travel videos');
	const productivityVideos = await getVideos('productivity videos');
	const popularVideos = await getVideos('popular videos in Myanmar');

	const { issuer } = verifyToken(token);
	let watchAgainVideos = await fetchWatchAgain(token, issuer);

	watchAgainVideos = watchAgainVideos.map(
		({ videoId, favourited, watched }) => {
			return {
				videoId,
				favourited,
				title: watched,
				imgUrl: `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`,
			};
		}
	);
	return {
		props: {
			disneyVideos: disneyVideos || [],
			travelVideos: travelVideos || [],
			productivityVideos: productivityVideos || [],
			popularVideos: popularVideos || [],
			watchAgainVideos: watchAgainVideos || [],
		}, // will be passed to the page component as props
	};
}
export default function Home({
	disneyVideos,
	travelVideos,
	productivityVideos,
	popularVideos,
	watchAgainVideos,
}) {
	return (
		<div className={style.home}>
			<Head>
				<title> NETFLIX CLONE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<CardContainer title="Action" cardSize="large" data={disneyVideos} />
			<CardContainer
				title="Watch Again"
				cardSize="small"
				data={watchAgainVideos}
			/>
			<CardContainer title="Travel" cardSize="medium" data={travelVideos} />
			<CardContainer
				title="Productivity"
				cardSize="small"
				data={productivityVideos}
			/>
			<CardContainer
				title="Popular Videos in MM"
				cardSize="medium"
				data={popularVideos}
			/>
		</div>
	);
}
