import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header/Header';
import CardContainer from '../components/CardContainer/CardContainer';
import { useEffect } from 'react';
import { getVideos } from '../youtube/youtube';
import style from '../styles/Home.module.css';
export async function getServerSideProps(context) {
	const disneyVideos = await getVideos('disney movies');
	const travelVideos = await getVideos('travel videos');
	const productivityVideos = await getVideos('productivity videos');
	const popularVideos = await getVideos('popular videos in Myanmar');
	console.log('DISNEY VIDEOS ---', disneyVideos);
	return {
		props: {
			disneyVideos: disneyVideos || [],
			travelVideos: travelVideos || [],
			productivityVideos: productivityVideos || [],
			popularVideos: popularVideos || [],
		}, // will be passed to the page component as props
	};
}
export default function Home({
	disneyVideos,
	travelVideos,
	productivityVideos,
	popularVideos,
}) {
	useEffect(() => {
		// const get = async () => {
		// 	const res = await fetch(
		// 		`https:youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=20&q=disney movies&key=AIzaSyDn59b8t5I0KQcO1tdt-vXg_4epdG-qB4g`
		// 	);
		// 	const data = await res.json();
		// 	console.log('Youtube Data ', data.items);
		// };
		// get();
		const get = async () => {
			const res = await getVideos('real madrid highlights');
			console.log('CALLED FROM INDEX --- ', res);
		};
		// get();
	}, []);

	// console.log('DISNEY', typeof disneyVideos);
	// console.log('TRAVEL', typeof travelVideos);
	// console.log('PRODUCTIVITY', productivityVideos);
	return (
		<div className={style.home}>
			<Head>
				<title> NETFLIX CLONE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<CardContainer title="Disney" cardSize="large" data={disneyVideos} />
			<CardContainer title="Travel" cardSize="medium" data={travelVideos} />
			<CardContainer
				title="Productivity"
				cardSize="small"
				data={productivityVideos}
			/>
			<CardContainer
				title="Popular Videos in MM"
				cardSize="medium"
				data={popularVideos}
			/>
		</div>
	);
}
