import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header/Header';
import CardContainer from '../components/CardContainer/CardContainer';
export default function Home() {
	return (
		<div>
			<Head>
				<title> NETFLIX CLONE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<CardContainer title="Disney" cardSize="large" />
			<CardContainer title="Travel" cardSize="medium" />
			<CardContainer title="Productivity" cardSize="small" />
			<CardContainer title="Popular" cardSize="medium" />
		</div>
	);
}
